In [1]:
import pandas as pd
import fsspec
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [3]:
url =  "https://raw.githubusercontent.com/kevin19925/RecursosParaCursos/refs/heads/main/sucursal_1.csv"
df = pd.read_csv(url, header=0)
print(df.head())

  ID_venta    Sucursal       Fecha  ID_producto        Nombre_producto  \
0    V1000  Sucursal 1  2023-03-01            3  Auriculares Bluetooth
1    V1001  Sucursal 1  2023-01-29            8                 Tablet
2    V1002  Sucursal 1  2023-02-16            6  Auriculares Bluetooth
3    V1003  Sucursal 1  2023-03-10           10  Auriculares Bluetooth
4    V1004  Sucursal 1  2023-03-13            7                  Reloj

  Categoría_producto  Precio_unitario  Cantidad_vendida  Monto_total  \
0               Ropa             80.0                 1        400.0
1        Electronica             40.0                 7        280.0
2         Accesorios             80.0                 1        480.0
3               Ropa             80.0                 7        800.0
4               Ropa            120.0                 9        320.0

  ID_empleado Nombre_empleado  Evaluación_atención  Descuento  \
0          E3     Pedro Gomez                    2         10
1          E5      Jose Lopez                    5          5
2          E4  Lucia Martinez                    1          5
3          E5  Lucia Martinez                    5         20
4          E2      Jose Lopez                    2          0

  Ubicación_cliente     Ciudad         Método_pago Hora_venta
0            Zona 1       Loja  Tarjeta de credito      Noche
1            Zona 2  Guayaquil  Tarjeta de credito     Mañana
2            Zona 3     Ambato            Efectivo      Tarde
3            Zona 3  Guayaquil              PayPal      Tarde
4            Zona 1     Ambato              PayPal     Mañana

In [15]:
print(df.tail())

    ID_venta    Sucursal      Fecha  ID_producto       Nombre_producto  \
495    V1495  Sucursal 1 2023-02-23            5     Chaqueta de cuero
496    V1496  Sucursal 1 2023-03-17            5                Tablet
497    V1497  Sucursal 1 2023-03-05            1            Smartphone
498    V1498  Sucursal 1 2023-01-01            1                Tablet
499    V1499  Sucursal 1 2023-01-07            5  Cargador inalambrico

    Categoría_producto  Precio_unitario  Cantidad_vendida  Monto_total  \
495               Ropa             40.0                 5       1000.0
496        Electronica             30.0                 8        480.0
497        Electronica            500.0                 3        500.0
498               Ropa             30.0                 1         40.0
499        Electronica             80.0                 9        480.0

    ID_empleado Nombre_empleado  Evaluación_atención  Descuento  \
495          E2     Pedro Gomez                    1          5
496          E4     Pedro Gomez                    3         10
497          E2    Carlos Perez                    5         15
498          E5    Carlos Perez                    3         15
499          E3     Pedro Gomez                    4         10

    Ubicación_cliente  Ciudad         Método_pago Hora_venta
495            Zona 1    Loja   Tarjeta de debito      Noche
496            Zona 2    Loja       Transferencia      Tarde
497            Zona 3  Cuenca              PayPal     Mañana
498            Zona 1    Loja  Tarjeta de credito     Mañana
499            Zona 1  Cuenca   Tarjeta de debito      Tarde

# 0. tratamiento de datos

In [4]:
print(df.dtypes)

ID_venta                object
Sucursal                object
Fecha                   object
ID_producto              int64
Nombre_producto         object
Categoría_producto      object
Precio_unitario        float64
Cantidad_vendida         int64
Monto_total            float64
ID_empleado             object
Nombre_empleado         object
Evaluación_atención      int64
Descuento                int64
Ubicación_cliente       object
Ciudad                  object
Método_pago             object
Hora_venta              object
dtype: object

In [9]:
df['Fecha']=pd.to_datetime(df['Fecha'])
df['Categoría_producto']=pd.Categorical(df['Categoría_producto'])
df['Método_pago']=pd.Categorical(df['Método_pago'])

In [10]:
print(df.dtypes)

ID_venta                       object
Sucursal                       object
Fecha                  datetime64[ns]
ID_producto                     int64
Nombre_producto                object
Categoría_producto           category
Precio_unitario               float64
Cantidad_vendida                int64
Monto_total                   float64
ID_empleado                    object
Nombre_empleado                object
Evaluación_atención             int64
Descuento                       int64
Ubicación_cliente              object
Ciudad                         object
Método_pago                  category
Hora_venta                     object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_venta             500 non-null    object
 1   Sucursal             500 non-null    object
 2   Fecha                500 non-null    datetime64[ns]
 3   ID_producto          500 non-null    int64
 4   Nombre_producto      500 non-null    object
 5   Categoría_producto   500 non-null    category
 6   Precio_unitario      490 non-null    float64
 7   Cantidad_vendida     500 non-null    int64
 8   Monto_total          490 non-null    float64
 9   ID_empleado          500 non-null    object
 10  Nombre_empleado      500 non-null    object
 11  Evaluación_atención  500 non-null    int64
 12  Descuento            500 non-null    int64
 13  Ubicación_cliente    500 non-null    object
 14  Ciudad               500 non-null    object
 15  Método_pago          500 non-null    category
 16  Hora_venta           500 non-null    object
dtypes: category(2), datetime64[ns](1), float64(2), int64(4), object(8)
memory usage: 60.1+ KB

In [14]:
df_nulosMonto=df.loc[df["Monto_total"].isna()]
df_nulosMonto[["Nombre_producto","Monto_total"]]

           Nombre_producto  Monto_total
108                  Reloj          NaN
145     Zapatos deportivos          NaN
154               Camiseta          NaN
282                 Tablet          NaN
397   Cargador inalambrico          NaN
398             Smartphone          NaN
452                 Tablet          NaN
456  Auriculares Bluetooth          NaN
464             Smartphone          NaN
474             Pantalones          NaN

In [18]:
df.loc[df["Nombre_producto"]=="Smartphone"]

,ID_venta,Sucursal,Fecha,ID_producto,Nombre_producto,Categoría_producto,Precio_unitario,Cantidad_vendida,Monto_total,ID_empleado,Nombre_empleado,Evaluación_atención,Descuento,Ubicación_cliente,Ciudad,Método_pago,Hora_venta
14,V1014,Sucursal 1,2023-03-15,10,Smartphone,Electronica,40.0,8,360.0,E3,Lucia Martinez,3,20,Zona 1,Quito,Tarjeta de credito,Mañana
26,V1026,Sucursal 1,2023-03-04,6,Smartphone,Electronica,80.0,3,600.0,E4,Ana Garcia,1,15,Zona 2,Guayaquil,Tarjeta de credito,Mañana
34,V1034,Sucursal 1,2023-01-04,10,Smartphone,Electronica,40.0,5,560.0,E1,Ana Garcia,5,20,Zona 3,Ambato,Transferencia,Tarde
36,V1036,Sucursal 1,2023-01-02,1,Smartphone,Electronica,25.0,1,4000.0,E5,Ana Garcia,5,10,Zona 1,Guayaquil,PayPal,Noche
51,V1051,Sucursal 1,2023-03-12,5,Smartphone,Electronica,500.0,6,240.0,E4,Pedro Gomez,5,0,Zona 2,Quito,Efectivo,Noche
61,V1061,Sucursal 1,2023-02-05,1,Smartphone,Calzado,500.0,2,480.0,E5,Jose Lopez,5,10,Zona 3,Cuenca,Tarjeta de credito,Mañana
69,V1069,Sucursal 1,2023-02-15,8,Smartphone,Electronica,300.0,2,1500.0,E4,Lucia Martinez,4,20,Zona 1,Cuenca,Tarjeta de debito,Mañana
80,V1080,Sucursal 1,2023-03-31,1,Smartphone,Calzado,300.0,7,60.0,E3,Carlos Perez,4,15,Zona 3,Ambato,Transferencia,Noche
82,V1082,Sucursal 1,2023-03-25,3,Smartphone,Accesorios,25.0,6,480.0,E3,Pedro Gomez,2,15,Zona 2,Cuenca,Tarjeta de debito,Tarde
95,V1095,Sucursal 1,2023-01-14,8,Smartphone,Accesorios,60.0,7,25.0,E2,Jose Lopez,2,10,Zona 2,Cuenca,Efectivo,Tarde
109,V1109,Sucursal 1,2023-03-08,4,Smartphone,Ropa,80.0,7,3500.0,E4,Ana Garcia,3,5,Zona 2,Guayaquil,Tarjeta de debito,Tarde
116,V1116,Sucursal 1,2023-03-12,6,Smartphone,Ropa,250.0,6,600.0,E3,Ana Garcia,5,0,Zona 1,Quito,Tarjeta de credito,Mañana
123,V1123,Sucursal 1,2023-01-13,7,Smartphone,Electronica,40.0,3,75.0,E2,Lucia Martinez,5,15,Zona 3,Ambato,Tarjeta de debito,Noche
152,V1152,Sucursal 1,2023-04-01,2,Smartphone,Calzado,60.0,4,1080.0,E2,Jose Lopez,2,5,Zona 1,Ambato,Transferencia,Mañana
162,V1162,Sucursal 1,2023-01-28,10,Smartphone,Ropa,25.0,4,720.0,E2,Carlos Perez,3,20,Zona 3,Ambato,Tarjeta de credito,Mañana
175,V1175,Sucursal 1,2023-02-23,5,Smartphone,Accesorios,500.0,10,640.0,E2,Carlos Perez,4,15,Zona 2,Guayaquil,Transferencia,Mañana
181,V1181,Sucursal 1,2023-02-24,1,Smartphone,Electronica,25.0,6,225.0,E3,Carlos Perez,3,20,Zona 1,Cuenca,Tarjeta de debito,Tarde
185,V1185,Sucursal 1,2023-03-26,10,Smartphone,Electronica,120.0,1,90.0,E4,Lucia Martinez,5,20,Zona 2,Ambato,Transferencia,Noche
190,V1190,Sucursal 1,2023-02-21,10,Smartphone,Accesorios,500.0,9,120.0,E2,Carlos Perez,2,10,Zona 3,Guayaquil,PayPal,Mañana
193,V1193,Sucursal 1,2023-01-05,8,Smartphone,Calzado,30.0,5,540.0,E3,Pedro Gomez,3,0,Zona 2,Ambato,Efectivo,Noche
203,V1203,Sucursal 1,2023-02-23,2,Smartphone,Electronica,250.0,8,360.0,E3,Carlos Perez,4,15,Zona 2,Quito,PayPal,Tarde
229,V1229,Sucursal 1,2023-02-24,9,Smartphone,Electronica,60.0,3,240.0,E1,Pedro Gomez,3,0,Zona 3,Cuenca,PayPal,Tarde
240,V1240,Sucursal 1,2023-02-12,6,Smartphone,Electronica,250.0,9,200.0,E1,Carlos Perez,1,0,Zona 1,Loja,Tarjeta de debito,Mañana
245,V1245,Sucursal 1,2023-02-27,9,Smartphone,Accesorios,30.0,4,25.0,E3,Lucia Martinez,2,20,Zona 1,Quito,Transferencia,Tarde
249,V1249,Sucursal 1,2023-01-13,8,Smartphone,Ropa,30.0,9,400.0,E1,Pedro Gomez,4,0,Zona 2,Cuenca,Transferencia,Tarde
256,V1256,Sucursal 1,2023-03-07,2,Smartphone,Electronica,120.0,1,200.0,E1,Lucia Martinez,3,20,Zona 1,Cuenca,PayPal,Noche
274,V1274,Sucursal 1,2023-01-15,8,Smartphone,Accesorios,250.0,3,4000.0,E5,Pedro Gomez,1,20,Zona 2,Ambato,Transferencia,Mañana
290,V1290,Sucursal 1,2023-02-16,3,Smartphone,Accesorios,30.0,10,750.0,E1,Lucia Martinez,5,20,Zona 1,Ambato,Tarjeta de credito,Mañana
320,V1320,Sucursal 1,2023-02-18,7,Smartphone,Ropa,150.0,2,250.0,E3,Pedro Gomez,2,20,Zona 1,Guayaquil,Tarjeta de credito,Noche
337,V1337,Sucursal 1,2023-01-29,4,Smartphone,Accesorios,500.0,4,300.0,E2,Pedro Gomez,3,0,Zona 1,Guayaquil,Tarjeta de credito,Mañana
340,V1340,Sucursal 1,2023-03-02,3,Smartphone,Ropa,25.0,4,300.0,E1,Jose Lopez,5,15,Zona 1,Loja,Tarjeta de credito,Noche
342,V1342,Sucursal 1,2023-01-08,9,Smartphone,Electronica,120.0,10,480.0,E4,Pedro Gomez,3,0,Zona 3,Cuenca,Efectivo,Mañana
357,V1357,Sucursal 1,2023-03-03,1,Smartphone,Calzado,60.0,2,720.0,E2,Lucia Martinez,2,0,Zona 1,Guayaquil,PayPal,Noche
360,V1360,Sucursal 1,2023-02-03,1,Smartphone,Electronica,120.0,4,420.0,E1,Jose Lopez,1,10,Zona 1,Ambato,Efectivo,Mañana
379,V1379,Sucursal 1,2023-02-26,7,Smartphone,Calzado,60.0,7,480.0,E1,Pedro Gomez,5,0,Zona 3,Quito,PayPal,Tarde
384,V1384,Sucursal 1,2023-03-11,9,Smartphone,Accesorios,120.0,5,250.0,E5,Ana Garcia,2,20,Zona 1,Loja,Efectivo,Mañana
398,V1398,Sucursal 1,2023-03-14,9,Smartphone,Ropa,NaN,4,NaN,E4,Carlos Perez,2,10,Zona 3,Loja,PayPal,Mañana
405,V1405,Sucursal 1,2023-03-27,7,Smartphone,Electronica,25.0,4,560.0,E1,Pedro Gomez,5,5,Zona 1,Cuenca,Tarjeta de debito,Tarde
408,V1408,Sucursal 1,2023-01-31,9,Smartphone,Accesorios,60.0,4,1250.0,E5,Carlos Perez,2,10,Zona 1,Loja,Tarjeta de debito,Tarde
410,V1410,Sucursal 1,2023-03-30,10,Smartphone,Electronica,80.0,9,900.0,E3,Pedro Gomez,5,0,Zona 2,Quito,Tarjeta de credito,Tarde
412,V1412,Sucursal 1,2023-01-29,5,Smartphone,Electronica,60.0,7,600.0,E3,Lucia Martinez,2,20,Zona 2,Quito,Transferencia,Mañana
413,V1413,Sucursal 1,2023-03-01,10,Smartphone,Calzado,250.0,8,480.0,E2,Lucia Martinez,1,10,Zona 2,Cuenca,Efectivo,Noche
423,V1423,Sucursal 1,2023-03-31,6,Smartphone,Electronica,60.0,10,3000.0,E3,Ana Garcia,2,20,Zona 2,Quito,Tarjeta de credito,Tarde
443,V1443,Sucursal 1,2023-02-06,9,Smartphone,Electronica,25.0,4,280.0,E4,Pedro Gomez,5,10,Zona 2,Loja,PayPal,Tarde
444,V1444,Sucursal 1,2023-03-09,2,Smartphone,Electronica,120.0,10,640.0,E3,Ana Garcia,2,0,Zona 3,Loja,Efectivo,Noche
454,V1454,Sucursal 1,2023-01-17,9,Smartphone,Electronica,80.0,4,480.0,E3,Pedro Gomez,1,10,Zona 2,Ambato,Tarjeta de credito,Tarde
455,V1455,Sucursal 1,2023-03-18,9,Smartphone,Accesorios,80.0,7,120.0,E3,Ana Garcia,4,20,Zona 1,Cuenca,Tarjeta de debito,Tarde
464,V1464,Sucursal 1,2023-01-19,2,Smartphone,Calzado,NaN,10,NaN,E4,Pedro Gomez,5,15,Zona 1,Quito,Tarjeta de debito,Mañana
473,V1473,Sucursal 1,2023-01-26,8,Smartphone,Electronica,30.0,5,3000.0,E1,Ana Garcia,3,5,Zona 1,Cuenca,Efectivo,Noche
479,V1479,Sucursal 1,2023-03-07,10,Smartphone,Electronica,300.0,2,40.0,E1,Jose Lopez,2,15,Zona 1,Guayaquil,Tarjeta de debito,Mañana
482,V1482,Sucursal 1,2023-01-21,10,Smartphone,Electronica,40.0,1,1000.0,E3,Pedro Gomez,3,0,Zona 3,Loja,PayPal,Tarde
497,V1497,Sucursal 1,2023-03-05,1,Smartphone,Electronica,500.0,3,500.0,E2,Carlos Perez,5,15,Zona 3,Cuenca,PayPal,Mañana

In [23]:
## datos se ven muy inconsistentes
# Agrupamos por producto y categoría para ver la variación de precios
df_inconulta = df.groupby(["Nombre_producto", "Categoría_producto"])["Precio_unitario"].agg(["min", "max", "mean", "std"])

print(df_inconulta)

                                           min    max        mean         std
Nombre_producto       Categoría_producto
Auriculares Bluetooth Accesorios          25.0  500.0  190.000000  159.745892
                      Calzado             30.0  300.0  125.714286  107.060286
                      Electronica         25.0  500.0  165.937500  140.561004
                      Ropa                25.0  500.0  158.461538  141.750729
Bicicleta             Accesorios          25.0  500.0  132.812500  129.460016
                      Calzado             60.0  500.0  245.000000  198.242276
                      Electronica         25.0  500.0  167.142857  132.733311
                      Ropa                25.0  500.0  156.071429  144.796655
Camiseta              Accesorios          30.0  500.0  248.181818  191.354027
                      Calzado             25.0  300.0  103.750000  131.743121
                      Electronica         25.0  500.0  161.470588  131.384035
                      Ropa                25.0  500.0  128.571429  170.309995
Cargador inalambrico  Accesorios          25.0  300.0  143.076923  118.331076
                      Calzado             25.0  500.0  135.625000  165.128467
                      Electronica         25.0  500.0  106.739130  116.400647
                      Ropa                25.0  500.0  222.083333  190.638381
Chaqueta de cuero     Accesorios          25.0  500.0  137.500000  161.868431
                      Calzado             30.0  250.0  176.666667  127.017059
                      Electronica         25.0  500.0  187.307692  170.741220
                      Ropa                25.0  500.0  136.190476  143.351881
Pantalones            Accesorios          30.0  300.0  141.111111  112.854380
                      Calzado             60.0  500.0  175.000000  216.871698
                      Electronica         25.0  300.0  160.000000  127.253029
                      Ropa                25.0  300.0  107.500000   97.108944
Reloj                 Accesorios          60.0  500.0  270.000000  220.680765
                      Calzado             25.0   80.0   48.125000   17.307616
                      Electronica         25.0  500.0  102.000000  119.883716
                      Ropa                25.0  300.0  142.352941  102.912549
Smartphone            Accesorios          25.0  500.0  195.909091  205.119699
                      Calzado             30.0  500.0  180.000000  176.729549
                      Electronica         25.0  500.0  131.153846  137.049682
                      Ropa                25.0  250.0   93.333333   90.866202
Tablet                Accesorios          30.0  500.0  195.294118  146.078645
                      Calzado             25.0  300.0   82.857143  101.400902
                      Electronica         25.0  500.0  126.750000  127.900815
                      Ropa                30.0  500.0  198.333333  171.296305
Zapatos deportivos    Accesorios          25.0  300.0  113.750000  119.724386
                      Calzado             80.0  500.0  307.500000  224.109348
                      Electronica         25.0  500.0  117.380952  148.118357
                      Ropa                30.0  500.0  158.571429  134.155888

/tmp/ipykernel_6889/1005246000.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_inconulta = df.groupby(["Nombre_producto", "Categoría_producto"])["Precio_unitario"].agg(["min", "max", "mean", "std"])

In [27]:
# df_inconulta2 = df.groupby(["Nombre_producto", "ID_producto"])["Categoría_producto"].count()

# df_inconulta2

df_inconulta2 = df.groupby(["Nombre_producto", "ID_producto"]).agg(
    categoriaCount=("Categoría_producto","count"),
    precio_promedio=("Precio_unitario", "mean"),
    varianza_precio=("Precio_unitario", "var")
)

df_inconulta2

                                   categoriaCount  precio_promedio  \
Nombre_producto       ID_producto
Auriculares Bluetooth 2                         4       230.000000
                      3                         3       290.000000
                      4                         7       169.285714
                      5                         5       106.000000
                      6                         2        52.500000
...                                           ...              ...
Zapatos deportivos    6                         5       195.000000
                      7                         4        88.750000
                      8                         2       155.000000
                      9                         2        40.000000
                      10                        4       160.000000

                                   varianza_precio
Nombre_producto       ID_producto
Auriculares Bluetooth 2                5933.333333
                      3               88200.000000
                      4               16636.904762
                      5                6780.000000
                      6                1512.500000
...                                            ...
Zapatos deportivos    6               32000.000000
                      7                5006.250000
                      8               18050.000000
                      9                        NaN
                      10              51933.333333

[99 rows x 3 columns]

In [29]:
# Corrección: Agregamos paréntesis a cada condición
df_incongruente3 = df.loc[(df["Nombre_producto"] == "Bicicleta") & (df["ID_producto"] == 10)]

df_incongruente3

,ID_venta,Sucursal,Fecha,ID_producto,Nombre_producto,Categoría_producto,Precio_unitario,Cantidad_vendida,Monto_total,ID_empleado,Nombre_empleado,Evaluación_atención,Descuento,Ubicación_cliente,Ciudad,Método_pago,Hora_venta
276,V1276,Sucursal 1,2023-03-31,10,Bicicleta,Accesorios,40.0,7,5000.0,E4,Lucia Martinez,1,15,Zona 2,Cuenca,Tarjeta de debito,Noche
313,V1313,Sucursal 1,2023-01-26,10,Bicicleta,Electronica,25.0,2,25.0,E3,Ana Garcia,3,10,Zona 3,Ambato,PayPal,Noche
366,V1366,Sucursal 1,2023-01-10,10,Bicicleta,Accesorios,80.0,7,60.0,E4,Ana Garcia,4,5,Zona 2,Ambato,PayPal,Tarde
439,V1439,Sucursal 1,2023-03-29,10,Bicicleta,Calzado,120.0,4,200.0,E4,Ana Garcia,4,10,Zona 2,Loja,Transferencia,Noche
450,V1450,Sucursal 1,2023-03-27,10,Bicicleta,Electronica,250.0,9,4500.0,E3,Ana Garcia,3,15,Zona 1,Loja,PayPal,Noche
451,V1451,Sucursal 1,2023-03-11,10,Bicicleta,Ropa,25.0,4,3500.0,E5,Ana Garcia,1,5,Zona 3,Cuenca,Tarjeta de credito,Mañana
457,V1457,Sucursal 1,2023-02-19,10,Bicicleta,Electronica,300.0,3,150.0,E1,Ana Garcia,3,10,Zona 1,Loja,Transferencia,Tarde

In [ ]:
# 1 Ciales son los productos mas vendidos durante los primeros 3 meses del anio

In [31]:
print(df['Categoría_producto'].value_counts())
print(df['Nombre_producto'].value_counts())

Categoría_producto
Electronica    189
Ropa           143
Accesorios     108
Calzado         60
Name: count, dtype: int64
Nombre_producto
Tablet                   58
Cargador inalambrico     57
Smartphone               52
Reloj                    49
Zapatos deportivos       48
Pantalones               48
Bicicleta                48
Chaqueta de cuero        47
Camiseta                 47
Auriculares Bluetooth    46
Name: count, dtype: int64